/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.HubEdition.RuntimePlatform;
namespace ssTeste_SAP {

	/// <summary>
	/// User Defined Exception class: UserException1
	/// </summary>
	public class ExcptUserException1: UserException {

		/// <summary>
		/// User Defined Exception (UserException1) constructor:
		/// </summary>
		public ExcptUserException1(string message)
		: base(message) {}
	}
}
