/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Sms;
using OutSystems.HubEdition.RuntimePlatform.Log;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;
using OutSystems.HubEdition.RuntimePlatform.Email;
using OutSystems.HubEdition.RuntimePlatform.Web;
using OutSystems.RuntimeCommon;
using OutSystems.ObjectKeys;
using System.Resources;

namespace ssTeste_SAP {

	public partial class Actions {
		public class CcJsonplaceholderTypicodeCallbacks: ICcJsonplaceholderTypicodeCallbacks {
			public static CcJsonplaceholderTypicodeCallbacks NewInstance() {
				return new CcJsonplaceholderTypicodeCallbacks();
			}
			private Dictionary<string, string> extendedPropValues = null;
			public string EvaluateExtendedProperty(HeContext heContext, string name) {
				if (extendedPropValues == null) {
					extendedPropValues = new Dictionary<string, string>();
				}
				return extendedPropValues[name];
			}
		}

	}

}