/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.ObjectKeys;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.RuntimeCommon;
namespace ssTeste_SAP {

	public class DefaultValues {
		public static int ReferenceWebFlow_Common_ReferenceWebBlock_Menu_Variables_ReferenceSerializableInputParameter_ActiveMenuItemId {
			get {
				return 0; 
			}
		}

		public static int ReferenceWebFlow_Common_ReferenceWebBlock_Menu_Variables_ReferenceSerializableInputParameter_ActiveSubMenuItemId {
			get {
				return 0; 
			}
		}

		public static int ReferenceEntity_MenuSubItem_ReferenceEntityAttribute_MenuItemId {
			get {
				return 0; 
			}
		}

	}
}
