<%@ Page Language="c#" Codebehind="MyInfo.aspx.cs" AutoEventWireup="false" Inherits="ssTeste_SAP.Flows.FlowCommon.ScrnMyInfo" %><%@ Register TagPrefix="osweb" Namespace="OutSystems.HubEdition.WebWidgets" Assembly="OutSystems.HubEdition.WebWidgets" %><%@ Assembly Name="OutSystems.WidgetsRuntimeAPI" %><%@ Import namespace="ssTeste_SAP" %><%@ Import namespace="OutSystems.HubEdition.RuntimePlatform" %><%@ Register TagPrefix="RichWidgets_widgets" TagName="KH_KQJACwvEqFcQnMKeaEzA" Src="Blocks\Teste_SAP\Layouts\Layout_London.ascx" %><%@ Register TagPrefix="widgets" TagName="KgGqVjlDuvkKTxk7naaerTA" Src="Blocks\Teste_SAP\Common\Header.ascx" %><%@ Register TagPrefix="widgets" TagName="Ke77LnY3GBfWtQXGOyBElgw" Src="Blocks\Teste_SAP\Common\Menu.ascx" %><%@ Register TagPrefix="Users_widgets" TagName="KctWZ_esj_kuK_h4cO5oIqA" Src="Blocks\Teste_SAP\UserManagement\EditMyInfo.ascx" %><%@ Register TagPrefix="Users_widgets" TagName="KQWN_E9RQQkSYKKIat9bWkw" Src="Blocks\Teste_SAP\UserManagement\ChangePassword.ascx" %><%@ Register TagPrefix="widgets" TagName="KRB2mbz7DZROG8vWnVIJNgw" Src="Blocks\Teste_SAP\Common\Footer.ascx" %>
<%= Teste_SAP_Properties.DocType %>
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server"><%= GetHeadTopJavaScript() %>
	<title><%= HttpUtility.HtmlEncode (Title) %></title>
    <meta http-equiv="Content-Type" content="<%= "text/html; charset=" + Response.ContentEncoding.WebName %>" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
<%= "\n" + GetStyleSheetIncludes() %><%= GetRequestInfoJavaScript() + GetJavaScriptIncludes() + GetHeadBottomJavaScript() %>
  </head>
  <osweb:Body runat="server"><%= GetBodyTopJavaScript() %>
    <osweb:Form id="WebForm1" method="post"  action="<%# GetFormAction() %>" runat="server">
<RichWidgets_widgets:KH_KQJACwvEqFcQnMKeaEzA runat="server" id="RichWidgets_wt_WebBlockInstance17" OnEvaluateParameters="RichWidgets_webBlck_WebBlockInstance17_onDataBinding" InstanceID="_WebBlockInstance17"><phHeader><widgets:KgGqVjlDuvkKTxk7naaerTA runat="server" id="wt_WebBlockInstance19" OnEvaluateParameters="webBlck_WebBlockInstance19_onDataBinding" InstanceID="_WebBlockInstance19"></widgets:KgGqVjlDuvkKTxk7naaerTA></phHeader><phMenu><widgets:Ke77LnY3GBfWtQXGOyBElgw runat="server" id="wt_WebBlockInstance11" OnEvaluateParameters="webBlck_WebBlockInstance11_onDataBinding" InstanceID="_WebBlockInstance11"></widgets:Ke77LnY3GBfWtQXGOyBElgw></phMenu><phTitle><osweb:PlaceHolder runat="server"><%# "My Info" %></osweb:PlaceHolder></phTitle><phActions><osweb:LinkButton runat="server" id="wt_Link8" onDataBinding="lnk_Link8_onDataBinding" cssClass="ActionChange" Visible="<%# lnk_Link8_isVisible() %>" Enabled="<%# lnk_Link8_isEnabled() %>" CausesValidation="false"><osweb:PlaceHolder runat="server"><%# "Change Password" %></osweb:PlaceHolder></osweb:LinkButton></phActions><phMainContent><osweb:Container runat="server" id="wtDivRefresh" onDataBinding="cntDivRefresh_onDataBinding"><osweb:IfPlaceHolder runat="server"><osweb:If runat="server" visible="<%# if_wt_If12() %>"><Users_widgets:KctWZ_esj_kuK_h4cO5oIqA runat="server" id="Users_wt_WebBlockInstance1" onAjaxNotify="Users_webBlck_WebBlockInstance1_AjaxNotify" OnEvaluateParameters="Users_webBlck_WebBlockInstance1_onDataBinding" OnBindDelegates="Users_webBlck_WebBlockInstance1_BindDelegates" InstanceID="_WebBlockInstance1"></Users_widgets:KctWZ_esj_kuK_h4cO5oIqA></osweb:If><osweb:If runat="server" visible="<%# !if_wt_If12() %>"><Users_widgets:KQWN_E9RQQkSYKKIat9bWkw runat="server" id="Users_wt_WebBlockInstance2" onAjaxNotify="Users_webBlck_WebBlockInstance2_AjaxNotify" OnEvaluateParameters="Users_webBlck_WebBlockInstance2_onDataBinding" OnBindDelegates="Users_webBlck_WebBlockInstance2_BindDelegates" InstanceID="_WebBlockInstance2"></Users_widgets:KQWN_E9RQQkSYKKIat9bWkw></osweb:If></osweb:IfPlaceHolder></osweb:Container></phMainContent><phFooter><widgets:KRB2mbz7DZROG8vWnVIJNgw runat="server" id="wt_WebBlockInstance18" OnEvaluateParameters="webBlck_WebBlockInstance18_onDataBinding" InstanceID="_WebBlockInstance18"></widgets:KRB2mbz7DZROG8vWnVIJNgw></phFooter></RichWidgets_widgets:KH_KQJACwvEqFcQnMKeaEzA><osweb:DummySubmitLink runat="server" id="Dummy_Submit_Link"/>
    <%= OutSystems.HubEdition.RuntimePlatform.AppInfo.GetAppInfo().GetWatermark() %><%= GetCallbackDebug()	
%><%= GetVisitCode() %></osweb:Form><%= GetEndPageJavaScript() + GetBodyBottomJavaScript() %>
  </osweb:Body>
</html>
