/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using OutSystems.RuntimeCommon.LogUtils;
using OutSystems.RuntimeCommon.ObfuscationProperties;

namespace OutSystems.HubEdition.RuntimePlatform.Log {
    
    [DoNotObfuscateType]
    internal class PublishLog : IPublishLog {

        public void LogPublishTrace(DateTime instant, int milliseconds, string eSpaceKey, string step, bool isStart, int traceKindId, string extraInfo, string parentStep) {
            if (Settings.GetBool(Settings.Configs.Log_CollectOneClickPublishMetrics)) {
                RuntimeLogger.LogPublishTrace(instant, milliseconds, eSpaceKey, step, isStart, traceKindId, extraInfo, parentStep);
            }
        }
    }
}
