/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;

namespace ssTeste_SAP {
	public class RLInput_AutoComplete_ListEntryRecordListTypeFactoryImpl: RsseSpaceRichWidgets.IRLInput_AutoComplete_ListEntryRecordListTypeFactory {
		private static readonly RLInput_AutoComplete_ListEntryRecordListTypeFactoryImpl Instance = new RLInput_AutoComplete_ListEntryRecordListTypeFactoryImpl();

		private RLInput_AutoComplete_ListEntryRecordListTypeFactoryImpl() {}

		public static void InitializeFactory() {
			RsseSpaceRichWidgets.Factory.FactoryRLInput_AutoComplete_ListEntryRecordListSingleton = Instance;

		}

		public RecordList CreateRsseSpaceRichWidgetsRLInput_AutoComplete_ListEntryRecordList() {
			return new RLInput_AutoComplete_ListEntryRecordList();
		}

	}
}