/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Sms;
using OutSystems.HubEdition.RuntimePlatform.Log;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;
using OutSystems.HubEdition.RuntimePlatform.Email;
using OutSystems.HubEdition.RuntimePlatform.Web;
using OutSystems.RuntimeCommon;
using OutSystems.ObjectKeys;
using System.Resources;

namespace ssTeste_SAP {

	public partial class Actions {
		/// <summary>
		/// Action <code>ActionUser_Login</code> that represents the Service Studio reference action
		///  <code>User_Login</code> <p> Description: Action to login using username and password a
		/// s credentials.  The User_Login action has the following behavior: 1-if found local user with
		///  password, 1.1-login with local user; 2-if active directory is on 2.1-i
		/// f Authentication.ValidateLogin(username,password) is ok 2.1.1-create or update user  The
		///  Authentication.ValidateLogin API uses the server domain controller to validate the login.  Th
		/// e RememberLogin adds a persistent cookie in the browser valid for 10 days. This value can be
		///  customized in "OutSystems.HubEdition.RememberLoginTimeoutInDays" ossys_parameter.</p>
		/// </summary>
		public static void ActionUser_Login(HeContext heContext, string inParamUsername, string inParamPassword, bool inParamRememberLogin) {
			RsseSpaceUsers.MssUser_Login(heContext, inParamUsername, inParamPassword, inParamRememberLogin);
		}

	}


}