/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;

namespace OutSystems.RuntimeCommon {

    [Flags, Serializable]
    public enum MessageType {
        Info = 1,
        Warning = 2,
        Error = 4,
        DevWarn = 8,
        Ok = 16,
        Question = 32,
        State = 64,
        TestRunning = 128,
    }
}