/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

namespace OutSystems.RuntimeCommon.Cryptography
{
    /// <summary>
    /// NOTE: This algorithm is FIPS compliant...
    /// </summary>
    public static class SignatureHelper
    {
        /// <summary>
        /// Signs the plain text with Hash-based Message Authentication Code (HMAC) using the <see cref="T:System.Security.Cryptography.SHA1"/>.
        /// </summary>
        /// <param name="plainText">The plain text.</param>
 		/// <param name="key">
        /// The secret key for encryption.
        /// The key can have any length but if it is more than 64 bytes long, it will be hashed
        ///  to derive a 64-byte key. Therefore, the recommended size of the secret key is 64 bytes.
        /// </param>
        /// <returns>The signed(hashed) text in Base64.</returns>
        /// <example>string signedString = SignatureHelper.Sign("This is a text example", "asdfEWFADScsdcAsadas13");</example>
        /// <author>dfs</author>
        /// <datetime>18-01-2013-11:44</datetime>
        public static string Sign(string plainText, string key) {
            return CryptManager.Instance.Sign(plainText, key);
        }

        /// <summary>
        /// Signs the array of bytes using Hash-based Message Authentication Code (HMAC) using the <see cref="T:System.Security.Cryptography.SHA1"/>.
        /// </summary>
        /// <param name="bytes">the array of bytes to be signed.</param>
        /// <param name="key">
        /// The secret key for encryption.
        /// The key can have any length but if it is more than 64 bytes long, it will be hashed
        ///  to derive a 64-byte key. Therefore, the recommended size of the secret key is 64 bytes.
        /// </param>
        /// <returns>The signed(hashed) text in Base64.</returns>
        /// <example>string signedStringFromBytes = SignatureHelper.Sign(arrBytes, "asdfEWFADScsdcAsadas13");</example>
        /// <author>dfs</author>
        /// <datetime>18-01-2013-11:44</datetime>
        public static string Sign(byte[] bytes, string key) {
            return CryptManager.Instance.Sign(bytes, key);
        }
    }
}